services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    environment:
      - FLAG=CTF{cs1rf_c00k1e_t0ss1ng_ftw}

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "8888:8888"
    depends_on:
      - app
    environment:
      - APP_URL=http://app:5000
